AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - lib/rbtoon/generated_parser.rb
    - test/**/*
  NewCops: enable
  SuggestExtensions: false

Layout/EndOfLine:
  EnforcedStyle: lf

Naming/PredicateMethod:
  AllowedMethods:
    - to_ruby

Naming/VariableNumber:
  EnforcedStyle: snake_case
  CheckSymbols: false

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/EmptyCaseCondition:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/RaiseArgs:
  EnforcedStyle: compact

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
