# frozen_string_literal: true
#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "toon.y".
#

require 'racc/parser.rb'
module RbToon
  class GeneratedParser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
    16,    23,    24,    25,    26,    27,    60,    23,    24,    25,
    26,    27,     4,    16,    16,     5,    28,    40,    36,    39,
    23,    24,    25,    26,    27,     4,    16,    16,     5,    23,
    24,    45,    16,    23,    24,    25,    26,    27,    48,    23,
    24,    25,    26,    27,    48,    16,    23,    24,    25,    26,
    27,    16,    23,    24,    25,    26,    27,    90,    23,    24,
    25,    26,    27,    90,    23,    24,    25,    26,    27,    23,
    24,   -58,    23,    24,    25,    26,    27,    23,    24,    25,
    26,    27,    23,    24,    23,    24,    23,    24,    30,    31,
   -67,    27,    41,    42,    43,    53,    65,    74,    76,    77,
    78,    60,    80,    74,    84,    85,    88,    94,    60,    97,
   -77,    74,    80,   105,    85,   108,    74,   112,    97,   115,
    60,   108,    74 ]

racc_action_check = [
     0,    39,    39,    39,    39,    39,    39,     0,     0,     0,
     0,     0,     0,     2,    10,     0,     1,    17,    10,    17,
     2,     2,     2,     2,     2,     2,    36,    34,     2,     9,
     9,    34,    45,    36,    36,    36,    36,    36,    36,    45,
    45,    45,    45,    45,    45,    64,    42,    42,    42,    42,
    42,   108,    64,    64,    64,    64,    64,    64,   108,   108,
   108,   108,   108,   108,    68,    68,    68,    68,    68,    32,
    32,    68,    80,    80,    80,    80,    80,    97,    97,    97,
    97,    97,    40,    40,    77,    77,    85,    85,     3,     8,
    11,    15,    18,    19,    28,    38,    41,    48,    49,    51,
    54,    55,    56,    60,    61,    62,    63,    66,    67,    70,
    75,    76,    81,    84,    86,    89,    90,    91,    98,   102,
   105,   109,   112 ]

racc_action_pointer = [
    -2,    16,    11,    70,   nil,   nil,   nil,   nil,    75,    20,
    12,    76,   nil,   nil,   nil,    78,   nil,    13,    77,    78,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    94,   nil,
   nil,   nil,    60,   nil,    25,   nil,    24,   nil,    87,    -8,
    73,    89,    37,   nil,   nil,    30,   nil,   nil,    80,    84,
   nil,    84,   nil,   nil,    97,    87,    94,   nil,   nil,   nil,
    86,    99,    97,    90,    43,   nil,    91,    94,    55,   nil,
   101,   nil,   nil,   nil,   nil,    95,    94,    75,   nil,   nil,
    63,   104,   nil,   nil,   107,    77,   106,   nil,   nil,   108,
    99,   103,   nil,   nil,   nil,   nil,   nil,    68,   110,   nil,
   nil,   nil,   103,   nil,   nil,   106,   nil,   nil,    49,   114,
   nil,   nil,   105,   nil,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_action_default = [
    -1,   -78,    -1,   -78,    -4,    -5,    -6,    -7,   -78,    -9,
   -78,   -14,   -24,   -25,   -26,   -78,   -30,   -78,   -38,   -50,
   -68,   -69,   -70,   -71,   -72,   -74,   -75,   -76,   -78,    -2,
    -3,    -8,    -9,   -11,   -78,   -17,   -78,   -13,   -27,   -73,
   -78,   -78,   -73,   120,   -10,   -78,   -16,   -12,   -18,   -78,
   -22,   -78,   -67,   -28,   -78,   -78,   -33,   -36,   -37,   -40,
   -18,   -78,   -54,   -78,   -78,   -45,   -78,   -78,   -73,   -60,
   -62,   -65,   -66,   -15,   -19,   -20,   -18,   -78,   -29,   -31,
   -73,   -33,   -35,   -77,   -78,   -78,   -54,   -56,   -39,   -42,
   -18,   -78,   -48,   -49,   -51,   -57,   -59,   -73,   -62,   -64,
   -21,   -14,   -78,   -32,   -34,   -78,   -53,   -55,   -78,   -42,
   -44,   -46,   -18,   -61,   -63,   -23,   -52,   -41,   -43,   -47 ]

racc_goto_table = [
     8,    11,     8,    11,    59,    37,    89,    75,    93,    99,
    35,    33,    56,    58,    87,     1,    69,    47,    82,    83,
    79,   102,    38,     3,   110,    29,    73,    54,    55,    46,
    63,    50,    95,    35,    44,   100,    49,   114,   107,    57,
    50,    62,    96,   104,   118,    49,    64,    66,    61,   111,
   117,   113,    93,   103,    58,   nil,   nil,   nil,   nil,    92,
   nil,   nil,   nil,   nil,    91,    11,   nil,   nil,   nil,   nil,
   116,   119,   nil,   nil,   nil,   nil,   nil,   nil,   101,   nil,
    57,   nil,   nil,   nil,   nil,   nil,   106,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    92,   nil,   nil,   nil,   nil,    91,    11 ]

racc_goto_check = [
     6,    12,     6,    12,    14,     5,    31,    15,     4,    44,
    12,     9,    24,    27,    38,     1,    41,    11,    26,    15,
    14,     4,    21,     3,    33,     3,    11,    22,    23,     5,
    29,     5,    14,    12,     9,    15,     6,    44,    38,     6,
     5,    12,    41,    26,    33,     6,    30,    35,    36,    15,
    31,    42,     4,    24,    27,   nil,   nil,   nil,   nil,     5,
   nil,   nil,   nil,   nil,     6,    12,   nil,   nil,   nil,   nil,
    14,    15,   nil,   nil,   nil,   nil,   nil,   nil,    12,   nil,
     6,   nil,   nil,   nil,   nil,   nil,    12,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     5,   nil,   nil,   nil,   nil,     6,    12 ]

racc_goto_pointer = [
   nil,    15,   nil,    23,   -56,    -5,     0,   nil,   nil,     2,
   nil,   -19,     1,   nil,   -35,   -41,   nil,   nil,   nil,   nil,
   nil,     7,   -11,   -11,   -27,   nil,   -38,   -26,   nil,   -11,
     5,   -58,   nil,   -65,   nil,     5,     8,   nil,   -48,   nil,
   nil,   -26,   -46,   nil,   -61,   nil,   nil ]

racc_goto_default = [
   nil,   nil,     2,   nil,     6,     7,    71,     9,    32,   nil,
    10,   nil,    52,    34,    51,   nil,    12,    13,    14,    17,
    15,    22,   nil,   nil,   nil,    81,   nil,    72,    18,   nil,
   nil,   nil,   109,   nil,    19,   nil,   nil,    86,   nil,    67,
    68,   nil,    70,    98,   nil,    20,    21 ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 23, :_reduce_1,
  2, 23, :_reduce_2,
  2, 21, :_reduce_none,
  1, 22, :_reduce_none,
  1, 22, :_reduce_none,
  1, 22, :_reduce_none,
  1, 22, :_reduce_none,
  2, 22, :_reduce_8,
  0, 29, :_reduce_9,
  2, 29, :_reduce_10,
  2, 24, :_reduce_11,
  3, 27, :_reduce_none,
  2, 27, :_reduce_none,
  1, 30, :_reduce_14,
  3, 28, :_reduce_none,
  2, 28, :_reduce_none,
  1, 33, :_reduce_17,
  0, 35, :_reduce_none,
  1, 35, :_reduce_none,
  2, 31, :_reduce_20,
  3, 31, :_reduce_21,
  1, 31, :_reduce_none,
  4, 31, :_reduce_none,
  1, 25, :_reduce_none,
  1, 25, :_reduce_none,
  1, 25, :_reduce_none,
  0, 42, :_reduce_none,
  1, 42, :_reduce_none,
  4, 39, :_reduce_29,
  1, 40, :_reduce_30,
  4, 36, :_reduce_31,
  2, 45, :_reduce_32,
  0, 46, :_reduce_33,
  2, 46, :_reduce_34,
  2, 43, :_reduce_35,
  1, 44, :_reduce_none,
  1, 44, :_reduce_none,
  1, 37, :_reduce_38,
  4, 37, :_reduce_39,
  3, 48, :_reduce_none,
  2, 52, :_reduce_41,
  0, 53, :_reduce_42,
  2, 53, :_reduce_43,
  3, 49, :_reduce_none,
  1, 50, :_reduce_45,
  2, 51, :_reduce_46,
  3, 51, :_reduce_47,
  1, 51, :_reduce_none,
  1, 51, :_reduce_none,
  1, 38, :_reduce_50,
  4, 38, :_reduce_51,
  6, 54, :_reduce_none,
  2, 57, :_reduce_53,
  0, 58, :_reduce_54,
  2, 58, :_reduce_55,
  2, 56, :_reduce_56,
  2, 60, :_reduce_57,
  1, 61, :_reduce_58,
  2, 61, :_reduce_59,
  1, 55, :_reduce_none,
  2, 63, :_reduce_61,
  0, 64, :_reduce_62,
  2, 64, :_reduce_63,
  2, 59, :_reduce_64,
  1, 62, :_reduce_none,
  1, 62, :_reduce_none,
  1, 26, :_reduce_none,
  1, 26, :_reduce_none,
  1, 26, :_reduce_none,
  1, 26, :_reduce_none,
  1, 32, :_reduce_71,
  1, 32, :_reduce_72,
  0, 47, :_reduce_73,
  1, 65, :_reduce_74,
  1, 66, :_reduce_75,
  1, 41, :_reduce_76,
  2, 34, :_reduce_77 ]

racc_reduce_n = 78

racc_shift_n = 120

racc_token_table = {
  false => 0,
  :error => 1,
  :L_BRACKET => 2,
  :R_BRACKET => 3,
  :L_BRACE => 4,
  :R_BRACE => 5,
  :COLON => 6,
  :HYPHEN => 7,
  :DELIMITER => 8,
  :QUOTED_STRING => 9,
  :UNQUOTED_STRING => 10,
  :BOOLEAN => 11,
  :NULL => 12,
  :NUMBER => 13,
  :NL => 14,
  :PUSH_INDENT => 15,
  :POP_INDENT => 16,
  :BLANK => 17,
  :EOS => 18,
  "-temp-group" => 19 }

racc_nt_base = 20

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "L_BRACKET",
  "R_BRACKET",
  "L_BRACE",
  "R_BRACE",
  "COLON",
  "HYPHEN",
  "DELIMITER",
  "QUOTED_STRING",
  "UNQUOTED_STRING",
  "BOOLEAN",
  "NULL",
  "NUMBER",
  "NL",
  "PUSH_INDENT",
  "POP_INDENT",
  "BLANK",
  "EOS",
  "\"-temp-group\"",
  "$start",
  "root",
  "root_item",
  "\"-many@root_item\"",
  "object",
  "array",
  "primitive",
  "object_head_item",
  "object_item",
  "\"-many@object_item\"",
  "object_head_key",
  "object_value",
  "string",
  "object_key",
  "nl_blank",
  "\"-option@BLANK\"",
  "inline_array",
  "list_array",
  "tebular_array",
  "array_header_common",
  "array_header_start",
  "number",
  "\"-option@DELIMITER\"",
  "inline_array_values",
  "inline_array_value",
  "\"-group@DELIMITER-inline_array_value\"",
  "\"-many@-group@DELIMITER-inline_array_value\"",
  "empty_string",
  "list_array_header",
  "list_array_items",
  "list_array_start",
  "list_array_value",
  "\"-group@HYPHEN-list_array_value\"",
  "\"-many@-group@HYPHEN-list_array_value\"",
  "tebular_array_header",
  "tabular_rows",
  "tabular_fields",
  "\"-group@DELIMITER-string\"",
  "\"-many@-group@DELIMITER-string\"",
  "tabular_row",
  "\"-group@tabular_row-nl_blank\"",
  "\"-many1@-group@tabular_row-nl_blank\"",
  "tabular_row_value",
  "\"-group@DELIMITER-tabular_row_value\"",
  "\"-many@-group@DELIMITER-tabular_row_value\"",
  "boolean",
  "null" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'toon.y', 25)
  def _reduce_1(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 25)
  def _reduce_2(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

module_eval(<<'.,.,', 'toon.y', 29)
  def _reduce_8(val, _values, result)
            handler.push_value(val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 39)
  def _reduce_9(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 39)
  def _reduce_10(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 34)
  def _reduce_11(val, _values, result)
            handler.pop
        scanner.pop_object

    result
  end
.,.,

# reduce 12 omitted

# reduce 13 omitted

module_eval(<<'.,.,', 'toon.y', 42)
  def _reduce_14(val, _values, result)
            handler.push_object(val[0])
        scanner.push_object

    result
  end
.,.,

# reduce 15 omitted

# reduce 16 omitted

module_eval(<<'.,.,', 'toon.y', 50)
  def _reduce_17(val, _values, result)
            handler.push_value(val[0])

    result
  end
.,.,

# reduce 18 omitted

# reduce 19 omitted

module_eval(<<'.,.,', 'toon.y', 54)
  def _reduce_20(val, _values, result)
            handler.push_empty_object(val[0].position)
        handler.push_blank(val[1])

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 58)
  def _reduce_21(val, _values, result)
            handler.push_value(val[0])
        handler.push_blank(val[2])

    result
  end
.,.,

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

module_eval(<<'.,.,', 'toon.y', 70)
  def _reduce_29(val, _values, result)
            scanner.delimiter(val[2])
        handler.push_array(val[0], val[1])

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 75)
  def _reduce_30(val, _values, result)
            scanner.push_array

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 79)
  def _reduce_31(val, _values, result)
            handler.pop
        scanner.pop_array

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 88)
  def _reduce_32(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 88)
  def _reduce_33(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 88)
  def _reduce_34(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 84)
  def _reduce_35(val, _values, result)
            handler.push_values(to_list(val))

    result
  end
.,.,

# reduce 36 omitted

# reduce 37 omitted

module_eval(<<'.,.,', 'toon.y', 91)
  def _reduce_38(val, _values, result)
            handler.pop
        scanner.pop_array

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 95)
  def _reduce_39(val, _values, result)
            handler.pop
        scanner.pop_array

    result
  end
.,.,

# reduce 40 omitted

module_eval(<<'.,.,', 'toon.y', 104)
  def _reduce_41(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 104)
  def _reduce_42(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 104)
  def _reduce_43(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

# reduce 44 omitted

module_eval(<<'.,.,', 'toon.y', 104)
  def _reduce_45(val, _values, result)
            scanner.start_list_array_items

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 108)
  def _reduce_46(val, _values, result)
            handler.push_empty_object(val[0].position)
        handler.push_blank(val[1])

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 112)
  def _reduce_47(val, _values, result)
            handler.push_value(val[0])
        handler.push_blank(val[2])

    result
  end
.,.,

# reduce 48 omitted

# reduce 49 omitted

module_eval(<<'.,.,', 'toon.y', 119)
  def _reduce_50(val, _values, result)
            handler.pop
        scanner.pop_array

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 123)
  def _reduce_51(val, _values, result)
            handler.pop
        scanner.pop_array

    result
  end
.,.,

# reduce 52 omitted

module_eval(<<'.,.,', 'toon.y', 134)
  def _reduce_53(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 134)
  def _reduce_54(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 134)
  def _reduce_55(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 130)
  def _reduce_56(val, _values, result)
            handler.push_tabular_fields(to_list(val))

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 136)
  def _reduce_57(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 136)
  def _reduce_58(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 136)
  def _reduce_59(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

# reduce 60 omitted

module_eval(<<'.,.,', 'toon.y', 140)
  def _reduce_61(val, _values, result)
    result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 140)
  def _reduce_62(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 140)
  def _reduce_63(val, _values, result)
    result = val[1] ? val[1].unshift(val[0]) : val
    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 136)
  def _reduce_64(val, _values, result)
            handler.push_tabular_row(to_list(val))

    result
  end
.,.,

# reduce 65 omitted

# reduce 66 omitted

# reduce 67 omitted

# reduce 68 omitted

# reduce 69 omitted

# reduce 70 omitted

module_eval(<<'.,.,', 'toon.y', 149)
  def _reduce_71(val, _values, result)
            result = handler.quoted_string(val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 152)
  def _reduce_72(val, _values, result)
            result = handler.unquoted_string(val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 156)
  def _reduce_73(val, _values, result)
            position = scanner.current_position
        result = handler.empty_string(position)

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 161)
  def _reduce_74(val, _values, result)
            result = handler.boolean(val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 165)
  def _reduce_75(val, _values, result)
            result = handler.null(val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 169)
  def _reduce_76(val, _values, result)
            result = handler.number(val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 174)
  def _reduce_77(val, _values, result)
            handler.push_blank(val[1])

    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class GeneratedParser
end   # module RbToon
