# frozen_string_literal: true
#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "toon.y".
#

require 'racc/parser.rb'
module Toonrb
  class GeneratedParser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
     2,    12,    12,    27,    16,    17,    16,    17,    18,    19,
    20,    21,    22,    12,    21,    22,    23,    16,    17,    18,
    19,    20,    21,    22,    36,    16,    17,    18,    19,    20,
    21,    22,    16,    17,    18,    19,    20,   -20,   -20,    20,
    38,    40,    41 ]

racc_action_check = [
     1,     9,     1,     9,     5,     5,     1,     1,     1,     1,
     1,     1,     1,    27,     7,     7,     2,    27,    27,    27,
    27,    27,    27,    27,    29,    11,    11,    11,    11,    11,
    29,    29,    36,    36,    36,    36,    36,    10,    10,    12,
    32,    37,    40 ]

racc_action_pointer = [
   nil,     0,    16,   nil,   nil,    -2,   nil,     3,   nil,    -1,
    26,    19,    29,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    11,   nil,    19,
   nil,   nil,    35,   nil,   nil,   nil,    26,    38,   nil,   nil,
    38,   nil ]

racc_action_default = [
    -1,   -31,   -31,    -2,    -3,    -4,    -5,   -31,    -7,   -31,
   -12,   -17,   -31,   -21,   -22,   -23,   -24,   -25,   -26,   -27,
   -28,   -29,   -30,    42,    -8,   -12,    -6,   -31,   -11,   -31,
   -18,   -20,   -15,    -9,   -10,   -13,   -31,   -31,   -16,   -19,
   -31,   -14 ]

racc_goto_table = [
    25,     4,     3,     1,    28,    30,    31,    26,    24,    29,
    32,    37,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    33,    34,    35,
    39,    31 ]

racc_goto_check = [
     9,     3,     2,     1,     5,     6,     9,     3,     7,    11,
    12,    13,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,     3,     2,     3,
     6,     9 ]

racc_goto_pointer = [
   nil,     3,     1,     0,   nil,    -5,    -6,     3,   nil,    -5,
   nil,    -2,    -2,   -21,   nil,   nil ]

racc_goto_default = [
   nil,   nil,   nil,   nil,     5,     6,     7,     8,     9,    10,
    11,   nil,    15,   nil,    13,    14 ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 14, :_reduce_none,
  2, 14, :_reduce_none,
  2, 14, :_reduce_none,
  1, 15, :_reduce_none,
  1, 15, :_reduce_none,
  2, 15, :_reduce_6,
  1, 17, :_reduce_none,
  2, 17, :_reduce_none,
  3, 20, :_reduce_none,
  3, 20, :_reduce_none,
  2, 20, :_reduce_none,
  1, 21, :_reduce_12,
  3, 18, :_reduce_13,
  5, 23, :_reduce_14,
  0, 26, :_reduce_15,
  1, 26, :_reduce_16,
  0, 24, :_reduce_none,
  1, 24, :_reduce_18,
  3, 24, :_reduce_19,
  1, 19, :_reduce_none,
  1, 19, :_reduce_none,
  1, 19, :_reduce_none,
  1, 19, :_reduce_none,
  1, 22, :_reduce_24,
  1, 22, :_reduce_25,
  1, 27, :_reduce_26,
  1, 28, :_reduce_27,
  1, 25, :_reduce_28,
  1, 16, :_reduce_none,
  1, 16, :_reduce_none ]

racc_reduce_n = 31

racc_shift_n = 42

racc_token_table = {
  false => 0,
  :error => 1,
  :L_BRACKET => 2,
  :R_BRACKET => 3,
  :COLON => 4,
  :DELIMITER => 5,
  :QUOTED_STRING => 6,
  :UNQUOTED_STRING => 7,
  :BOOLEAN => 8,
  :NULL => 9,
  :NUMBER => 10,
  :NEWLINE => 11,
  :EOS => 12 }

racc_nt_base = 13

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "L_BRACKET",
  "R_BRACKET",
  "COLON",
  "DELIMITER",
  "QUOTED_STRING",
  "UNQUOTED_STRING",
  "BOOLEAN",
  "NULL",
  "NUMBER",
  "NEWLINE",
  "EOS",
  "$start",
  "root",
  "value",
  "eol",
  "object",
  "array",
  "primitive",
  "object_item",
  "object_key",
  "string",
  "array_header",
  "inline_array_values",
  "number",
  "delimiter",
  "boolean",
  "null" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

module_eval(<<'.,.,', 'toon.y', 25)
  def _reduce_6(val, _values, result)
            handler.push_value(val[0])

    result
  end
.,.,

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

module_eval(<<'.,.,', 'toon.y', 39)
  def _reduce_12(val, _values, result)
            handler.push_object_key(val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 45)
  def _reduce_13(val, _values, result)
            scanner.clear_delimiter

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 49)
  def _reduce_14(val, _values, result)
            array = Nodes::Array.new(val[0], val[1])
        handler.push_array(array)

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 54)
  def _reduce_15(val, _values, result)
            scanner.default_delimiter

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 57)
  def _reduce_16(val, _values, result)
            scanner.delimiter(val[0])

    result
  end
.,.,

# reduce 17 omitted

module_eval(<<'.,.,', 'toon.y', 63)
  def _reduce_18(val, _values, result)
            handler.push_value(val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 66)
  def _reduce_19(val, _values, result)
            handler.push_value(val[2])

    result
  end
.,.,

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

module_eval(<<'.,.,', 'toon.y', 78)
  def _reduce_24(val, _values, result)
            result = Toonrb::Nodes::QuotedString.new(val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 81)
  def _reduce_25(val, _values, result)
            result = Toonrb::Nodes::UnquotedString.new(val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 86)
  def _reduce_26(val, _values, result)
            result = Toonrb::Nodes::Boolean.new(val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 91)
  def _reduce_27(val, _values, result)
            result = Toonrb::Nodes::Null.new(val[0])

    result
  end
.,.,

module_eval(<<'.,.,', 'toon.y', 96)
  def _reduce_28(val, _values, result)
            result = Toonrb::Nodes::Number.new(val[0])

    result
  end
.,.,

# reduce 29 omitted

# reduce 30 omitted

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class GeneratedParser
end   # module Toonrb
