# frozen_string_literal: true
#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "toon.y".
#

require 'racc/parser.rb'
module Toonrb
  class GeneratedParser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
     2,     6,     5 ]

racc_action_check = [
     1,     2,     1 ]

racc_action_pointer = [
   nil,     0,     1,   nil,   nil,   nil,   nil ]

racc_action_default = [
    -1,    -8,    -8,    -3,    -5,    -7,     7 ]

racc_goto_table = [
     1,     3,     4 ]

racc_goto_check = [
     1,     2,     3 ]

racc_goto_pointer = [
   nil,     0,     0,     1 ]

racc_goto_default = [
   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 4, :_reduce_none,
  0, 4, :_reduce_none,
  2, 4, :_reduce_none,
  0, 5, :_reduce_none,
  1, 5, :_reduce_5,
  0, 6, :_reduce_none,
  1, 6, :_reduce_7 ]

racc_reduce_n = 8

racc_shift_n = 7

racc_token_table = {
  false => 0,
  :error => 1,
  :BOOLEAN => 2 }

racc_nt_base = 3

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "BOOLEAN",
  "$start",
  "root_objects",
  "root_object",
  "primitive" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = true

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

module_eval(<<'.,.,', 'toon.y', 9)
  def _reduce_5(val, _values, result)
     @handler.push_child(val[0])
    result
  end
.,.,

# reduce 6 omitted

module_eval(<<'.,.,', 'toon.y', 12)
  def _reduce_7(val, _values, result)
     result = Toonrb::Nodes::Boolean.new(val[0])
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class GeneratedParser
end   # module Toonrb
